//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace River.OneMoreAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("River.OneMoreAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the log file.
        /// </summary>
        internal static string AboutDialog_clearLogLabel_Text {
            get {
                return ResourceManager.GetString("AboutDialog_clearLogLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the log file now?.
        /// </summary>
        internal static string AboutDialog_ClearLogMessage {
            get {
                return ResourceManager.GetString("AboutDialog_ClearLogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No log file is available.
        /// </summary>
        internal static string AboutDialog_ClearLogNoneMessage {
            get {
                return ResourceManager.GetString("AboutDialog_ClearLogNoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s all good.
        /// </summary>
        internal static string AboutDialog_ClearLogNoneTitle {
            get {
                return ResourceManager.GetString("AboutDialog_ClearLogNoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string AboutDialog_ClearLogTitle {
            get {
                return ResourceManager.GetString("AboutDialog_ClearLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright @ 2016-{0} Steven M Cohn.
        /// </summary>
        internal static string AboutDialog_copyLabel_Text {
            get {
                return ResourceManager.GetString("AboutDialog_copyLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version.
        /// </summary>
        internal static string AboutDialog_LatestMessage {
            get {
                return ResourceManager.GetString("AboutDialog_LatestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re good to go!.
        /// </summary>
        internal static string AboutDialog_LatestTitle {
            get {
                return ResourceManager.GetString("AboutDialog_LatestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available:
        ///
        ///    {0} - &quot;{1}&quot;
        ///
        ///Do you want to update now?
        ///OneNote will close automatically.
        /// </summary>
        internal static string AboutDialog_NewVersionMessage {
            get {
                return ResourceManager.GetString("AboutDialog_NewVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update OneMore.
        /// </summary>
        internal static string AboutDialog_NewVersionTitle {
            get {
                return ResourceManager.GetString("AboutDialog_NewVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AboutDialog_okButton_Text {
            get {
                return ResourceManager.GetString("AboutDialog_okButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneMore Add-in for OneNote 2016.
        /// </summary>
        internal static string AboutDialog_titleLabel_Text {
            get {
                return ResourceManager.GetString("AboutDialog_titleLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string AboutDialog_updateLink_Text {
            get {
                return ResourceManager.GetString("AboutDialog_updateLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string AboutDialog_versionLabel_Text {
            get {
                return ResourceManager.GetString("AboutDialog_versionLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneMore Add-in.
        /// </summary>
        internal static string AboutDialoge_Text {
            get {
                return ResourceManager.GetString("AboutDialoge.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more cells from the same row or the same column.
        /// </summary>
        internal static string AddFormula_linearMessage {
            get {
                return ResourceManager.GetString("AddFormula_linearMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneMoreAddIn.
        /// </summary>
        internal static string AddInTitle {
            get {
                return ResourceManager.GetString("AddInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Architecture {
            get {
                object obj = ResourceManager.GetObject("Architecture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Automobile {
            get {
                object obj = ResourceManager.GetObject("Automobile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bold {
            get {
                object obj = ResourceManager.GetObject("Bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bullet {
            get {
                object obj = ResourceManager.GetObject("Bullet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Calendar {
            get {
                object obj = ResourceManager.GetObject("Calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Camera {
            get {
                object obj = ResourceManager.GetObject("Camera", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ChangePageColorDialog_cancelButton_Text {
            get {
                return ResourceManager.GetString("ChangePageColorDialog_cancelButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom background....
        /// </summary>
        internal static string ChangePageColorDialog_customButton_Text {
            get {
                return ResourceManager.GetString("ChangePageColorDialog_customButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark background.
        /// </summary>
        internal static string ChangePageColorDialog_darkButton_Text {
            get {
                return ResourceManager.GetString("ChangePageColorDialog_darkButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After choosing a page color, load one of the predefined styles or customize your own styles so all content has enough contrast to be visible..
        /// </summary>
        internal static string ChangePageColorDialog_introLabel_Text {
            get {
                return ResourceManager.GetString("ChangePageColorDialog_introLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light background.
        /// </summary>
        internal static string ChangePageColorDialog_lightButton_Text {
            get {
                return ResourceManager.GetString("ChangePageColorDialog_lightButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ChangePageColorDialog_okButton_Text {
            get {
                return ResourceManager.GetString("ChangePageColorDialog_okButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Page Color.
        /// </summary>
        internal static string ChangePageColorDialog_Text {
            get {
                return ResourceManager.GetString("ChangePageColorDialog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Circle {
            get {
                object obj = ResourceManager.GetObject("Circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cross {
            get {
                object obj = ResourceManager.GetObject("Cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomColors.xml.
        /// </summary>
        internal static string CustomColorsFilesname {
            get {
                return ResourceManager.GetString("CustomColorsFilesname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;CustomStyles&gt;
        ///  &lt;Style index=&quot;0&quot; name=&quot;Heading 1&quot; font=&quot;Calibri Light&quot; fontColor=&quot;Black&quot; fontSize=&quot;20.0&quot; spaceBefore=&quot;14.0&quot; spaceAfter=&quot;0.0&quot; applyColors=&quot;true&quot; styleType=&quot;Heading&quot; /&gt;
        ///  &lt;Style index=&quot;1&quot; name=&quot;Heading 2&quot; font=&quot;Calibri Light&quot; fontColor=&quot;#E67832&quot; fontSize=&quot;18.0&quot; spaceBefore=&quot;14.0&quot; spaceAfter=&quot;0.0&quot; applyColors=&quot;true&quot; styleType=&quot;Heading&quot; /&gt;
        ///  &lt;Style index=&quot;2&quot; name=&quot;Heading 3&quot; font=&quot;Calibri Light&quot; fontColor=&quot;#823D0A&quot; fontSize=&quot;16.0&quot; spaceBefore=&quot;12.0&quot; sp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomStyles {
            get {
                return ResourceManager.GetString("CustomStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomStyles.xml.
        /// </summary>
        internal static string CustomStylesFilename {
            get {
                return ResourceManager.GetString("CustomStylesFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cyclist {
            get {
                object obj = ResourceManager.GetObject("Cyclist", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoubleLine {
            get {
                object obj = ResourceManager.GetObject("DoubleLine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DownArrow {
            get {
                object obj = ResourceManager.GetObject("DownArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture.
        /// </summary>
        internal static string Emoji_Architecture {
            get {
                return ResourceManager.GetString("Emoji_Architecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automobile.
        /// </summary>
        internal static string Emoji_Automobile {
            get {
                return ResourceManager.GetString("Emoji_Automobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullet.
        /// </summary>
        internal static string Emoji_Bullet {
            get {
                return ResourceManager.GetString("Emoji_Bullet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Emoji_Calendar {
            get {
                return ResourceManager.GetString("Emoji_Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string Emoji_Circle {
            get {
                return ResourceManager.GetString("Emoji_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Mark.
        /// </summary>
        internal static string Emoji_CrossMark {
            get {
                return ResourceManager.GetString("Emoji_CrossMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycling.
        /// </summary>
        internal static string Emoji_Cycling {
            get {
                return ResourceManager.GetString("Emoji_Cycling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Emoji_Email {
            get {
                return ResourceManager.GetString("Emoji_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string Emoji_Family {
            get {
                return ResourceManager.GetString("Emoji_Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial.
        /// </summary>
        internal static string Emoji_Financial {
            get {
                return ResourceManager.GetString("Emoji_Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hammer.
        /// </summary>
        internal static string Emoji_Hammer {
            get {
                return ResourceManager.GetString("Emoji_Hammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Emoji_Images {
            get {
                return ResourceManager.GetString("Emoji_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important.
        /// </summary>
        internal static string Emoji_Important {
            get {
                return ResourceManager.GetString("Emoji_Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        internal static string Emoji_Journal {
            get {
                return ResourceManager.GetString("Emoji_Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memo.
        /// </summary>
        internal static string Emoji_Memo {
            get {
                return ResourceManager.GetString("Emoji_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords.
        /// </summary>
        internal static string Emoji_Passwords {
            get {
                return ResourceManager.GetString("Emoji_Passwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pencil.
        /// </summary>
        internal static string Emoji_Pencil {
            get {
                return ResourceManager.GetString("Emoji_Pencil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushpin.
        /// </summary>
        internal static string Emoji_Pushpin {
            get {
                return ResourceManager.GetString("Emoji_Pushpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shazam!.
        /// </summary>
        internal static string Emoji_Shazam {
            get {
                return ResourceManager.GetString("Emoji_Shazam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smiley.
        /// </summary>
        internal static string Emoji_Smiley {
            get {
                return ResourceManager.GetString("Emoji_Smiley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        internal static string Emoji_Software {
            get {
                return ResourceManager.GetString("Emoji_Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sports.
        /// </summary>
        internal static string Emoji_Sports {
            get {
                return ResourceManager.GetString("Emoji_Sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        internal static string Emoji_Star {
            get {
                return ResourceManager.GetString("Emoji_Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Emoji_Summary {
            get {
                return ResourceManager.GetString("Emoji_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Emoji_Tasks {
            get {
                return ResourceManager.GetString("Emoji_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel.
        /// </summary>
        internal static string Emoji_Travel {
            get {
                return ResourceManager.GetString("Emoji_Travel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        internal static string Emoji_Watch {
            get {
                return ResourceManager.GetString("Emoji_Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string EmojiDialog_cancelButton_Text {
            get {
                return ResourceManager.GetString("EmojiDialog_cancelButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select on or more icons to add to page title.
        /// </summary>
        internal static string EmojiDialog_introLabel_Text {
            get {
                return ResourceManager.GetString("EmojiDialog_introLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string EmojiDialog_okButton_Text {
            get {
                return ResourceManager.GetString("EmojiDialog_okButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TItle Icons.
        /// </summary>
        internal static string EmojiDialog_Text {
            get {
                return ResourceManager.GetString("EmojiDialog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Envelope {
            get {
                object obj = ResourceManager.GetObject("Envelope", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Family {
            get {
                object obj = ResourceManager.GetObject("Family", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.xml.
        /// </summary>
        internal static string FavoritesFilename {
            get {
                return ResourceManager.GetString("FavoritesFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Financial {
            get {
                object obj = ResourceManager.GetObject("Financial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Flag {
            get {
                object obj = ResourceManager.GetObject("Flag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number
        ///Currency
        ///Percentage.
        /// </summary>
        internal static string FomulaDialog_formatBox_Items {
            get {
                return ResourceManager.GetString("FomulaDialog_formatBox.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FontColor {
            get {
                object obj = ResourceManager.GetObject("FontColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string FormulaDialog_cancelButton_Text {
            get {
                return ResourceManager.GetString("FormulaDialog_cancelButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column cells above.
        /// </summary>
        internal static string FormulaDialog_colButton_Text {
            get {
                return ResourceManager.GetString("FormulaDialog_colButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        internal static string FormulaDialog_formatLabel_Text {
            get {
                return ResourceManager.GetString("FormulaDialog_formatLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum
        ///Average
        ///Min
        ///Max
        ///Range
        ///Median
        ///Mode
        ///Variance
        ///Standard Deviation.
        /// </summary>
        internal static string FormulaDialog_functionBox_Items {
            get {
                return ResourceManager.GetString("FormulaDialog_functionBox.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function:.
        /// </summary>
        internal static string FormulaDialog_functionLabel_Text {
            get {
                return ResourceManager.GetString("FormulaDialog_functionLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string FormulaDialog_okButton_Text {
            get {
                return ResourceManager.GetString("FormulaDialog_okButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range:.
        /// </summary>
        internal static string FormulaDialog_rangeLabel_Text {
            get {
                return ResourceManager.GetString("FormulaDialog_rangeLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row cells to the left.
        /// </summary>
        internal static string FormulaDialog_rowButton_Text {
            get {
                return ResourceManager.GetString("FormulaDialog_rowButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula.
        /// </summary>
        internal static string FormulaDialog_Text {
            get {
                return ResourceManager.GetString("FormulaDialog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hammer {
            get {
                object obj = ResourceManager.GetObject("Hammer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Italic {
            get {
                object obj = ResourceManager.GetObject("Italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Journal {
            get {
                object obj = ResourceManager.GetObject("Journal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Memo {
            get {
                object obj = ResourceManager.GetObject("Memo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewStyle {
            get {
                object obj = ResourceManager.GetObject("NewStyle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoSpellCheck {
            get {
                object obj = ResourceManager.GetObject("NoSpellCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering page {0}.
        /// </summary>
        internal static string NumberingPage_Message {
            get {
                return ResourceManager.GetString("NumberingPage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.smc.com/onemore/2020/styles.
        /// </summary>
        internal static string OneMoreNamespace {
            get {
                return ResourceManager.GetString("OneMoreNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneMore.
        /// </summary>
        internal static string OneMoreTab_Label {
            get {
                return ResourceManager.GetString("OneMoreTab_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/office/onenote/2013/onenote.
        /// </summary>
        internal static string oneNamespace {
            get {
                return ResourceManager.GetString("oneNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha-numeric.
        /// </summary>
        internal static string OutlineDialog_alphaRadio_Text {
            get {
                return ResourceManager.GetString("OutlineDialog_alphaRadio.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string OutlineDialog_cancelButton_Text {
            get {
                return ResourceManager.GetString("OutlineDialog_cancelButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove/cleanup existing numbering.
        /// </summary>
        internal static string OutlineDialog_cleanBox_Text {
            get {
                return ResourceManager.GetString("OutlineDialog_cleanBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indentations.
        /// </summary>
        internal static string OutlineDialog_indentationsGroup_Text {
            get {
                return ResourceManager.GetString("OutlineDialog_indentationsGroup.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent content below headings.
        /// </summary>
        internal static string OutlineDialog_indentBox_Text {
            get {
                return ResourceManager.GetString("OutlineDialog_indentBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent only below tagged headings/paragraphs.
        /// </summary>
        internal static string OutlineDialog_indentTagBox_Text {
            get {
                return ResourceManager.GetString("OutlineDialog_indentTagBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indents content below only tagged headings or non-tagged paragraphs.
        /// </summary>
        internal static string OutlineDialog_indentTagBox_Tooltip {
            get {
                return ResourceManager.GetString("OutlineDialog_indentTagBox.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Numbering.
        /// </summary>
        internal static string OutlineDialog_numberingBox_Text {
            get {
                return ResourceManager.GetString("OutlineDialog_numberingBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied to both standard and custom Headings.
        /// </summary>
        internal static string OutlineDialog_numberingBox_Tooltip {
            get {
                return ResourceManager.GetString("OutlineDialog_numberingBox.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering.
        /// </summary>
        internal static string OutlineDialog_numberingGroup_Text {
            get {
                return ResourceManager.GetString("OutlineDialog_numberingGroup.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        internal static string OutlineDialog_numRadio_Text {
            get {
                return ResourceManager.GetString("OutlineDialog_numRadio.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OutlineDialog_okButton_Text {
            get {
                return ResourceManager.GetString("OutlineDialog_okButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tags.
        /// </summary>
        internal static string OutlineDialog_removeTagsBox_Text {
            get {
                return ResourceManager.GetString("OutlineDialog_removeTagsBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag:.
        /// </summary>
        internal static string OutlineDialog_tagLabel_Text {
            get {
                return ResourceManager.GetString("OutlineDialog_tagLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline Formatting.
        /// </summary>
        internal static string OutlineDialog_Text {
            get {
                return ResourceManager.GetString("OutlineDialog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Color.
        /// </summary>
        internal static string PageColorDialog_Text {
            get {
                return ResourceManager.GetString("PageColorDialog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha-numeric.
        /// </summary>
        internal static string PageNumberingDialog_alphaRadio_Text {
            get {
                return ResourceManager.GetString("PageNumberingDialog_alphaRadio.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string PageNumberingDialog_cancelButton_Text {
            get {
                return ResourceManager.GetString("PageNumberingDialog_cancelButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove/cleanup existing numbering.
        /// </summary>
        internal static string PageNumberingDialog_cleanCheckbox_Text {
            get {
                return ResourceManager.GetString("PageNumberingDialog_cleanCheckbox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        internal static string PageNumberingDialog_numRadio_Text {
            get {
                return ResourceManager.GetString("PageNumberingDialog_numRadio.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PageNumberingDialog_okButton_Text {
            get {
                return ResourceManager.GetString("PageNumberingDialog_okButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Numbering.
        /// </summary>
        internal static string PageNumberingDialog_Text {
            get {
                return ResourceManager.GetString("PageNumberingDialog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Passwords {
            get {
                object obj = ResourceManager.GetObject("Passwords", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pencil {
            get {
                object obj = ResourceManager.GetObject("Pencil", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pushpin {
            get {
                object obj = ResourceManager.GetObject("Pushpin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing number from page {0}.
        /// </summary>
        internal static string RemovingPageNumber_Message {
            get {
                return ResourceManager.GetString("RemovingPageNumber_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Reorder {
            get {
                object obj = ResourceManager.GetObject("Reorder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ReorderDialog_cancelButton_Text {
            get {
                return ResourceManager.GetString("ReorderDialog_cancelButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder how styles appear in the gallery. Also changes the order of headings in a TOC.
        /// </summary>
        internal static string ReorderDialog_label_Text {
            get {
                return ResourceManager.GetString("ReorderDialog_label.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ReorderDialog_okButton_Text {
            get {
                return ResourceManager.GetString("ReorderDialog_okButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Custom Styles.
        /// </summary>
        internal static string ReorderDialog_Text {
            get {
                return ResourceManager.GetString("ReorderDialog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute.
        /// </summary>
        internal static string ResizeImagesDialog_absRadio_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog_absRadio.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all images on page.
        /// </summary>
        internal static string ResizeImagesDialog_allLabel_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog_allLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain aspect ratio.
        /// </summary>
        internal static string ResizeImagesDialog_aspectBox_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog_aspectBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ResizeImagesDialog_cancelButton_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog_cancelButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to.
        /// </summary>
        internal static string ResizeImagesDialog_currentLabel_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog_currentLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current size.
        /// </summary>
        internal static string ResizeImagesDialog_currentLabelSize_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog_currentLabelSize.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string ResizeImagesDialog_heightLabel_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog_heightLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ResizeImagesDialog_okButton_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog_okButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original size.
        /// </summary>
        internal static string ResizeImagesDialog_origLabel_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog_origLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} x {1}.
        /// </summary>
        internal static string ResizeImagesDialog_origSizeLink_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog_origSizeLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string ResizeImagesDialog_pctLabel_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog_pctLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string ResizeImagesDialog_pctRadio_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog_pctRadio.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string ResizeImagesDialog_presetLabel_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog_presetLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        internal static string ResizeImagesDialog_presetRadio_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog_presetRadio.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} x {1}.
        /// </summary>
        internal static string ResizeImagesDialog_sizeLink_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog_sizeLink.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize Image.
        /// </summary>
        internal static string ResizeImagesDialog_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string ResizeImagesDialog_widthLabel_Text {
            get {
                return ResourceManager.GetString("ResizeImagesDialog_widthLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About OneMore.
        /// </summary>
        internal static string ribAboutButton_Label {
            get {
                return ResourceManager.GetString("ribAboutButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Formula.
        /// </summary>
        internal static string ribAddFormulaButton_Label {
            get {
                return ResourceManager.GetString("ribAddFormulaButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add formula to selected table cell(s).
        /// </summary>
        internal static string ribAddFormulaButton_Screentip {
            get {
                return ResourceManager.GetString("ribAddFormulaButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Styles to Page.
        /// </summary>
        internal static string ribApplyStylesButton_Label {
            get {
                return ResourceManager.GetString("ribApplyStylesButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue Status.
        /// </summary>
        internal static string ribBlueStatusButton_Label {
            get {
                return ResourceManager.GetString("ribBlueStatusButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;customUI
        ///  xmlns=&quot;http://schemas.microsoft.com/office/2006/01/customui&quot;
        ///	onLoad=&quot;RibbonLoaded&quot;
        ///	loadImage=&quot;GetImage&quot;&gt;
        ///  &lt;ribbon&gt;
        ///    &lt;tabs&gt;
        ///      &lt;tab idMso=&quot;TabHome&quot;&gt;
        ///        &lt;group id=&quot;ribOneMoreGroup&quot; getLabel=&quot;GetItemLabel&quot;&gt;
        ///          &lt;gallery
        ///            id=&quot;ribCustomStylesButton&quot; columns=&quot;4&quot; showItemLabel=&quot;false&quot; size=&quot;large&quot; imageMso=&quot;StylesPane&quot;
        ///            getLabel=&quot;GetItemLabel&quot; 
        ///            getItemCount=&quot;GetStyleGalleryItemCount&quot;
        ///            g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Ribbon {
            get {
                return ResourceManager.GetString("Ribbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Caption.
        /// </summary>
        internal static string ribCaptionButton_Label {
            get {
                return ResourceManager.GetString("ribCaptionButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean....
        /// </summary>
        internal static string ribCleanMenu_Label {
            get {
                return ResourceManager.GetString("ribCleanMenu_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code block.
        /// </summary>
        internal static string ribCodeBlockButton_Label {
            get {
                return ResourceManager.GetString("ribCodeBlockButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Pages.
        /// </summary>
        internal static string ribCollapseButton_Label {
            get {
                return ResourceManager.GetString("ribCollapseButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Style from Selection....
        /// </summary>
        internal static string ribCreateStyleButton_Label {
            get {
                return ResourceManager.GetString("ribCreateStyleButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Styles.
        /// </summary>
        internal static string ribCustomStylesButton_Label {
            get {
                return ResourceManager.GetString("ribCustomStylesButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Font Size.
        /// </summary>
        internal static string ribDecreaseFontSizeButton_Label {
            get {
                return ResourceManager.GetString("ribDecreaseFontSizeButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease page font size (Ctrl + Alt + Minus).
        /// </summary>
        internal static string ribDecreaseFontSizeButton_Screentip {
            get {
                return ResourceManager.GetString("ribDecreaseFontSizeButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Formula.
        /// </summary>
        internal static string ribDeleteFormulaButton_Label {
            get {
                return ResourceManager.GetString("ribDeleteFormulaButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete formula from selected table cell(s).
        /// </summary>
        internal static string ribDeleteFormulaButton_Screentip {
            get {
                return ResourceManager.GetString("ribDeleteFormulaButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Styles....
        /// </summary>
        internal static string ribEditStylesButton_Label {
            get {
                return ResourceManager.GetString("ribEditStylesButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand/Collapse.
        /// </summary>
        internal static string ribExpandButton_Label {
            get {
                return ResourceManager.GetString("ribExpandButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras....
        /// </summary>
        internal static string ribExtrasMenu_Label {
            get {
                return ResourceManager.GetString("ribExtrasMenu_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string ribFavoritesMenu_Label {
            get {
                return ResourceManager.GetString("ribFavoritesMenu_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Icon to Page Title.
        /// </summary>
        internal static string ribFlagTitleButton_Label {
            get {
                return ResourceManager.GetString("ribFlagTitleButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Footnote.
        /// </summary>
        internal static string ribFootnoteButton_Label {
            get {
                return ResourceManager.GetString("ribFootnoteButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add footnote (Ctrl + Alt + F).
        /// </summary>
        internal static string ribFootnoteButton_Screentip {
            get {
                return ResourceManager.GetString("ribFootnoteButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Footnote.
        /// </summary>
        internal static string ribFootnoteRemoveButton_Label {
            get {
                return ResourceManager.GetString("ribFootnoteRemoveButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove footnote (Ctrl + Shift + F).
        /// </summary>
        internal static string ribFootnoteRemoveButton_Screentip {
            get {
                return ResourceManager.GetString("ribFootnoteRemoveButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula....
        /// </summary>
        internal static string ribFormulaMenu_Label {
            get {
                return ResourceManager.GetString("ribFormulaMenu_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray Status.
        /// </summary>
        internal static string ribGrayStatusButton_Label {
            get {
                return ResourceManager.GetString("ribGrayStatusButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Status.
        /// </summary>
        internal static string ribGreenStatusButton_Label {
            get {
                return ResourceManager.GetString("ribGreenStatusButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight Formula.
        /// </summary>
        internal static string ribHighlightFormulaButton_Label {
            get {
                return ResourceManager.GetString("ribHighlightFormulaButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High cells with formula in current table.
        /// </summary>
        internal static string ribHighlightFormulaButton_Screentip {
            get {
                return ResourceManager.GetString("ribHighlightFormulaButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images....
        /// </summary>
        internal static string ribImagesMenu_Label {
            get {
                return ResourceManager.GetString("ribImagesMenu_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Font Size.
        /// </summary>
        internal static string ribIncreaseFontSizeButton_Label {
            get {
                return ResourceManager.GetString("ribIncreaseFontSizeButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase page font size (Ctrl + Alt + Plus).
        /// </summary>
        internal static string ribIncreaseFontSizeButton_Screentip {
            get {
                return ResourceManager.GetString("ribIncreaseFontSizeButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info block.
        /// </summary>
        internal static string ribInfoBlockButton_Label {
            get {
                return ResourceManager.GetString("ribInfoBlockButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Double Horizontal Line.
        /// </summary>
        internal static string ribInsertDoubleLineButton_Label {
            get {
                return ResourceManager.GetString("ribInsertDoubleLineButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert double horizontal line (Shift + Alt + Equals).
        /// </summary>
        internal static string ribInsertDoubleLineButton_Screentip {
            get {
                return ResourceManager.GetString("ribInsertDoubleLineButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Horizontal Line.
        /// </summary>
        internal static string ribInsertSingleLineButton_Label {
            get {
                return ResourceManager.GetString("ribInsertSingleLineButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert single horizontal line (Shift + Alt + Minus).
        /// </summary>
        internal static string ribInsertSingleLineButton_Screentip {
            get {
                return ResourceManager.GetString("ribInsertSingleLineButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To lowercase.
        /// </summary>
        internal static string ribLowercaseButton_Label {
            get {
                return ResourceManager.GetString("ribLowercaseButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert text to lowercase (Ctrl + Shift + U).
        /// </summary>
        internal static string ribLowercaseButton_Screentip {
            get {
                return ResourceManager.GetString("ribLowercaseButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Pages.
        /// </summary>
        internal static string ribMergeButton_Label {
            get {
                return ResourceManager.GetString("ribMergeButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace URLs with Web Page Titles.
        /// </summary>
        internal static string ribNameUrlsButton_Label {
            get {
                return ResourceManager.GetString("ribNameUrlsButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Spell Check.
        /// </summary>
        internal static string ribNoSpellCheckButton_Label {
            get {
                return ResourceManager.GetString("ribNoSpellCheckButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable spell check for entire page (F4).
        /// </summary>
        internal static string ribNoSpellCheckButton_Screentip {
            get {
                return ResourceManager.GetString("ribNoSpellCheckButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering....
        /// </summary>
        internal static string ribNumberingMenu_Label {
            get {
                return ResourceManager.GetString("ribNumberingMenu_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pages.
        /// </summary>
        internal static string ribNumberPagesButton_Label {
            get {
                return ResourceManager.GetString("ribNumberPagesButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or update number of all pages in this section.
        /// </summary>
        internal static string ribNumberPagesButton_Screentip {
            get {
                return ResourceManager.GetString("ribNumberPagesButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Sections.
        /// </summary>
        internal static string ribNumberSectionsButton_Label {
            get {
                return ResourceManager.GetString("ribNumberSectionsButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or update numbering of all sections in this notebook.
        /// </summary>
        internal static string ribNumberSectionsButton_Screentip {
            get {
                return ResourceManager.GetString("ribNumberSectionsButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneMore.
        /// </summary>
        internal static string ribOneMoreGroup_Label {
            get {
                return ResourceManager.GetString("ribOneMoreGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        internal static string ribOneMoreMenu_Label {
            get {
                return ResourceManager.GetString("ribOneMoreMenu_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline Formatting.
        /// </summary>
        internal static string ribOutlineButton_Label {
            get {
                return ResourceManager.GetString("ribOutlineButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Page Color....
        /// </summary>
        internal static string ribPageColorButton_Label {
            get {
                return ResourceManager.GetString("ribPageColorButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Rich Text.
        /// </summary>
        internal static string ribPasteRtfButton_Label {
            get {
                return ResourceManager.GetString("ribPasteRtfButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste rich text (Ctrl + Alt + V).
        /// </summary>
        internal static string ribPasteRtfButton_Screentip {
            get {
                return ResourceManager.GetString("ribPasteRtfButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate Formula.
        /// </summary>
        internal static string ribRecalculateFormulaButton_Label {
            get {
                return ResourceManager.GetString("ribRecalculateFormulaButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate all formula in the current table.
        /// </summary>
        internal static string ribRecalculateFormulaButton_Screentip {
            get {
                return ResourceManager.GetString("ribRecalculateFormulaButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Status.
        /// </summary>
        internal static string ribRedStatusButton_Label {
            get {
                return ResourceManager.GetString("ribRedStatusButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Author Information.
        /// </summary>
        internal static string ribRemoveAuthorsButton_Label {
            get {
                return ResourceManager.GetString("ribRemoveAuthorsButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove information for all authors on this page.
        /// </summary>
        internal static string ribRemoveAuthorsButton_Screentip {
            get {
                return ResourceManager.GetString("ribRemoveAuthorsButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove empty paragraphs and headers.
        /// </summary>
        internal static string ribRemoveEmptyButton_Label {
            get {
                return ResourceManager.GetString("ribRemoveEmptyButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove extra empty lines between paragraph and remove empty headers.
        /// </summary>
        internal static string ribRemoveEmptyButton_Screentip {
            get {
                return ResourceManager.GetString("ribRemoveEmptyButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Page Numbers.
        /// </summary>
        internal static string ribRemovePageNumbersButton_Label {
            get {
                return ResourceManager.GetString("ribRemovePageNumbersButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove numbers from all pages in this section.
        /// </summary>
        internal static string ribRemovePageNumbersButton_Screentip {
            get {
                return ResourceManager.GetString("ribRemovePageNumbersButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Section Numbers.
        /// </summary>
        internal static string ribRemoveSectionNumbersButton_Label {
            get {
                return ResourceManager.GetString("ribRemoveSectionNumbersButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove numbers from all sectionsin this notebook.
        /// </summary>
        internal static string ribRemoveSectionNumbersButton_Screentip {
            get {
                return ResourceManager.GetString("ribRemoveSectionNumbersButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search and Replace.
        /// </summary>
        internal static string ribReplaceButton_Label {
            get {
                return ResourceManager.GetString("ribReplaceButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search and replace (Ctrl + H).
        /// </summary>
        internal static string ribReplaceButton_Screentip {
            get {
                return ResourceManager.GetString("ribReplaceButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        internal static string ribResizeImagesButton_Label {
            get {
                return ResourceManager.GetString("ribResizeImagesButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        internal static string ribSaveAsButton_Label {
            get {
                return ResourceManager.GetString("ribSaveAsButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save page as either HTML or XML.
        /// </summary>
        internal static string ribSaveAsButton_Screentip {
            get {
                return ResourceManager.GetString("ribSaveAsButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show XML.
        /// </summary>
        internal static string ribShowXmlButton_Label {
            get {
                return ResourceManager.GetString("ribShowXmlButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show XML of hierarchy and current page (Ctrl + Shift + Alt + X).
        /// </summary>
        internal static string ribShowXmlButton_Screentip {
            get {
                return ResourceManager.GetString("ribShowXmlButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snippets....
        /// </summary>
        internal static string ribSnippetsMenu_Label {
            get {
                return ResourceManager.GetString("ribSnippetsMenu_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort....
        /// </summary>
        internal static string ribSortButton_Label {
            get {
                return ResourceManager.GetString("ribSortButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Page TOC.
        /// </summary>
        internal static string ribTocButton_Label {
            get {
                return ResourceManager.GetString("ribTocButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Page Date and Time Stamps.
        /// </summary>
        internal static string ribToggleDttmButton_Label {
            get {
                return ResourceManager.GetString("ribToggleDttmButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/hide page date and time stamps below title.
        /// </summary>
        internal static string ribToggleDttmButton_Screentip {
            get {
                return ResourceManager.GetString("ribToggleDttmButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim Whitespace.
        /// </summary>
        internal static string ribTrimButton_Label {
            get {
                return ResourceManager.GetString("ribTrimButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim trailing whitespace from selected text.
        /// </summary>
        internal static string ribTrimButton_Screentip {
            get {
                return ResourceManager.GetString("ribTrimButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To UPPERCASE.
        /// </summary>
        internal static string ribUppercaseButton_Label {
            get {
                return ResourceManager.GetString("ribUppercaseButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert text to uppercase (Ctrl + Shift + Alt + U).
        /// </summary>
        internal static string ribUppercaseButton_Screentip {
            get {
                return ResourceManager.GetString("ribUppercaseButton_Screentip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning block.
        /// </summary>
        internal static string ribWarnBlockButton_Label {
            get {
                return ResourceManager.GetString("ribWarnBlockButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Status.
        /// </summary>
        internal static string ribYellowStatusButton_Label {
            get {
                return ResourceManager.GetString("ribYellowStatusButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SaveAs {
            get {
                object obj = ResourceManager.GetObject("SaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving page as {0}.
        /// </summary>
        internal static string SaveAs_Error {
            get {
                return ResourceManager.GetString("SaveAs_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML File|.htm|XML File|.xml.
        /// </summary>
        internal static string SaveAs_Filter {
            get {
                return ResourceManager.GetString("SaveAs_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file type must be either .htm or .xml.
        /// </summary>
        internal static string SaveAs_Invalid_Type {
            get {
                return ResourceManager.GetString("SaveAs_Invalid_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page saved to {0}.
        /// </summary>
        internal static string SaveAs_Success {
            get {
                return ResourceManager.GetString("SaveAs_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Page as....
        /// </summary>
        internal static string SaveAs_Title {
            get {
                return ResourceManager.GetString("SaveAs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SearchAndReplaceDialog_cancelButton_Text {
            get {
                return ResourceManager.GetString("SearchAndReplaceDialog_cancelButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        internal static string SearchAndReplaceDialog_matchBox_Text {
            get {
                return ResourceManager.GetString("SearchAndReplaceDialog_matchBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string SearchAndReplaceDialog_okButton_Text {
            get {
                return ResourceManager.GetString("SearchAndReplaceDialog_okButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search and Replace.
        /// </summary>
        internal static string SearchAndReplaceDialog_Text {
            get {
                return ResourceManager.GetString("SearchAndReplaceDialog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find what:.
        /// </summary>
        internal static string SearchAndReplaceDialog_whatLabel_Text {
            get {
                return ResourceManager.GetString("SearchAndReplaceDialog_whatLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with:.
        /// </summary>
        internal static string SearchAndReplaceDialog_withLabel_Text {
            get {
                return ResourceManager.GetString("SearchAndReplaceDialog_withLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.xml.
        /// </summary>
        internal static string SettingsFilename {
            get {
                return ResourceManager.GetString("SettingsFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Shazam {
            get {
                object obj = ResourceManager.GetObject("Shazam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Smiley {
            get {
                object obj = ResourceManager.GetObject("Smiley", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Software {
            get {
                object obj = ResourceManager.GetObject("Software", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string SortDialog_ascButton_Text {
            get {
                return ResourceManager.GetString("SortDialog_ascButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string SortDialog_cancelButton_Text {
            get {
                return ResourceManager.GetString("SortDialog_cancelButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        internal static string SortDialog_createdButton_Text {
            get {
                return ResourceManager.GetString("SortDialog_createdButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string SortDialog_desButton_Text {
            get {
                return ResourceManager.GetString("SortDialog_desButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction:.
        /// </summary>
        internal static string SortDialog_direcitonLabel_Text {
            get {
                return ResourceManager.GetString("SortDialog_direcitonLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        internal static string SortDialog_modifiedButton_Text {
            get {
                return ResourceManager.GetString("SortDialog_modifiedButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SortDialog_nameButton_Text {
            get {
                return ResourceManager.GetString("SortDialog_nameButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string SortDialog_okButton_Text {
            get {
                return ResourceManager.GetString("SortDialog_okButton.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin Notes to top and
        ///Quick Notes to bottom.
        /// </summary>
        internal static string SortDialog_pinNotesBox_Text {
            get {
                return ResourceManager.GetString("SortDialog_pinNotesBox.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages in this section
        ///Sections in this notebook
        ///Notebooks.
        /// </summary>
        internal static string SortDialog_scopeBox_Items {
            get {
                return ResourceManager.GetString("SortDialog_scopeBox.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope:.
        /// </summary>
        internal static string SortDialog_scopeLabel_Text {
            get {
                return ResourceManager.GetString("SortDialog_scopeLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        internal static string SortDialog_sortLabel_Text {
            get {
                return ResourceManager.GetString("SortDialog_sortLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string SortDialog_Text {
            get {
                return ResourceManager.GetString("SortDialog.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sports {
            get {
                object obj = ResourceManager.GetObject("Sports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Star {
            get {
                object obj = ResourceManager.GetObject("Star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Strikethrough {
            get {
                object obj = ResourceManager.GetObject("Strikethrough", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Subscript {
            get {
                object obj = ResourceManager.GetObject("Subscript", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Summary {
            get {
                object obj = ResourceManager.GetObject("Summary", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Superscript {
            get {
                object obj = ResourceManager.GetObject("Superscript", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tasks {
            get {
                object obj = ResourceManager.GetObject("Tasks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TextHighlightColorPicker {
            get {
                object obj = ResourceManager.GetObject("TextHighlightColorPicker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Travel {
            get {
                object obj = ResourceManager.GetObject("Travel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Underline {
            get {
                object obj = ResourceManager.GetObject("Underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UpArrow {
            get {
                object obj = ResourceManager.GetObject("UpArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Watch {
            get {
                object obj = ResourceManager.GetObject("Watch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
