//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneMoreCalendar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneMoreCalendar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;DarkMode&quot;: true,
        ///  &quot;Colors&quot;: {
        ///    &quot;BackColor&quot;: &quot;#383838&quot;,
        ///    &quot;ForeColor&quot;: &quot;#E6E6E6&quot;,
        ///    &quot;Border&quot;: &quot;DarkOrchid&quot;,
        ///    &quot;Control&quot;: &quot;MediumOrchid&quot;,
        ///    &quot;Highlight&quot;: &quot;#D2A1DF&quot;,
        ///    &quot;ButtonBack&quot;: &quot;#363636&quot;,
        ///    &quot;ButtonFore&quot;: &quot;#E6E6E6&quot;,
        ///    &quot;ButtonDisabled&quot;: &quot;Gray&quot;,
        ///    &quot;ButtonBorder&quot;: &quot;#555555&quot;,
        ///    &quot;ButtonHotBack&quot;: &quot;#505050&quot;,
        ///    &quot;ButtonHotBorder&quot;: &quot;Gray&quot;,
        ///    &quot;ButtonPressBorder&quot;: &quot;DarkOrchid&quot;,
        ///    &quot;LinkColor&quot;: &quot;MediumOrchid&quot;,
        ///    &quot;HoverColor&quot;: &quot;Orchid&quot;,
        ///    &quot;MonthHeader&quot;: &quot;#383838&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap day_32 {
            get {
                object obj = ResourceManager.GetObject("day_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;DarkMode&quot;: false,
        ///  &quot;Colors&quot;: {
        ///    &quot;BackColor&quot;: &quot;White&quot;,
        ///    &quot;ForeColor&quot;: &quot;Black&quot;,
        ///    &quot;Border&quot;: &quot;#D2A1DF&quot;,
        ///    &quot;Control&quot;: &quot;#73356E&quot;,
        ///    &quot;Highlight&quot;: &quot;#BC58B6&quot;,
        ///    &quot;ButtonBack&quot;: &quot;#F7EDF7&quot;,
        ///    &quot;ButtonFore&quot;: &quot;#73356E&quot;,
        ///    &quot;ButtonDisabled&quot;: &quot;Gray&quot;,
        ///    &quot;ButtonBorder&quot;: &quot;#F0DAEE&quot;,
        ///    &quot;ButtonHotBack&quot;: &quot;#F0DAEE&quot;,
        ///    &quot;ButtonHotBorder&quot;: &quot;#9E5499&quot;,
        ///    &quot;ButtonPressBorder&quot;: &quot;#9E5499&quot;,
        ///    &quot;LinkColor&quot;: &quot;#73356E&quot;,
        ///    &quot;HoverColor&quot;: &quot;MediumOrchid&quot;,
        ///    &quot;MonthHeader&quot;: &quot;Control&quot;,
        ///    &quot;MonthPri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap month_32 {
            get {
                object obj = ResourceManager.GetObject("month_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_32 {
            get {
                object obj = ResourceManager.GetObject("settings_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sponsor {
            get {
                object obj = ResourceManager.GetObject("Sponsor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SponsorOver {
            get {
                object obj = ResourceManager.GetObject("SponsorOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap today_32 {
            get {
                object obj = ResourceManager.GetObject("today_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
