//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneMoreTray.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneMoreTray.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneMoreTray.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneMoreTray was not started correctly and will close now.
        /// </summary>
        internal static string BadArguments {
            get {
                return ResourceManager.GetString("BadArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Schedule.
        /// </summary>
        internal static string BadArgumentsTitle {
            get {
                return ResourceManager.GetString("BadArgumentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close the tray application?.
        /// </summary>
        internal static string CloseConfirm {
            get {
                return ResourceManager.GetString("CloseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        internal static string phrase_Scanning {
            get {
                return ResourceManager.GetString("phrase_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A catalog rebuild is scheduled for {0}. Choose below when OneMore Tray should build the catalog..
        /// </summary>
        internal static string Reschedule_Rebuild {
            get {
                return ResourceManager.GetString("Reschedule_Rebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A scan for new hashtags is scheduled for {0}. Choose below when OneMore Tray should build the catalog..
        /// </summary>
        internal static string Reschedule_Scan {
            get {
                return ResourceManager.GetString("Reschedule_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run now.
        /// </summary>
        internal static string RunNowMenuItem {
            get {
                return ResourceManager.GetString("RunNowMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneMore Hashtag scanning is complete and ready to use!.
        /// </summary>
        internal static string ScanComplete {
            get {
                return ResourceManager.GetString("ScanComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Complete.
        /// </summary>
        internal static string ScanCompleteTitle {
            get {
                return ResourceManager.GetString("ScanCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashtag Scanner is scheduled for {0}. This can be adjusted from the OneMore Tray application..
        /// </summary>
        internal static string ScannerScheduled {
            get {
                return ResourceManager.GetString("ScannerScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashtag Scanner.
        /// </summary>
        internal static string ScannerTitle {
            get {
                return ResourceManager.GetString("ScannerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning can take quite some time and affect OneNote performance. If OneNote is closed during the scan, it cannot be reopened until the scan is completed.
        ///
        ///Cancel the scheduled time and run the scan now?.
        /// </summary>
        internal static string ScanNowConfirmation {
            get {
                return ResourceManager.GetString("ScanNowConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A scan is currently running.
        /// </summary>
        internal static string ScanRunning {
            get {
                return ResourceManager.GetString("ScanRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A scan is scheduled to run on {0}.
        /// </summary>
        internal static string ScanScheduled {
            get {
                return ResourceManager.GetString("ScanScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting scan now....
        /// </summary>
        internal static string ScanStarting {
            get {
                return ResourceManager.GetString("ScanStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled for {0}.
        /// </summary>
        internal static string ScheduledFor {
            get {
                return ResourceManager.GetString("ScheduledFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd, MMMM d, yyyy h:mm tt.
        /// </summary>
        internal static string ScheduleTimeFormat {
            get {
                return ResourceManager.GetString("ScheduleTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string word_Cancel {
            get {
                return ResourceManager.GetString("word_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string word_Exit {
            get {
                return ResourceManager.GetString("word_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string word_OK {
            get {
                return ResourceManager.GetString("word_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule.
        /// </summary>
        internal static string word_Reschedule {
            get {
                return ResourceManager.GetString("word_Reschedule", resourceCulture);
            }
        }
    }
}
